version: 0.0
os: linux
files:
  - source: /webapp/index.html
    destination: /webapp/html/
  - source: /webapp/index.js
    destination: /webapp/js/
  - source: /webapp/webcam.js
    destination: /webapp/js/
    
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
